#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build', 
          '-t', 
          'gcr.io/$PROJECT_ID/lnldocker-$BRANCH_NAME', 
          '.',
          '--build-arg', 'arg_app_name=${_APP_NAME}',
        ]
  env:
    - 'APP_NAME=$_APP_NAME'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/lnldocker-$BRANCH_NAME']
substitutions:
    _APP_NAME: appnametest # default value
images: ['gcr.io/$PROJECT_ID/lnldocker-$BRANCH_NAME']
tags: ['image-lnldocker-$BRANCH_NAME']