#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',         
          '-t', 
          'gcr.io/$PROJECT_ID/lnldocker-webapp-$BRANCH_NAME', 
          '.',
        ]
  dir: 'webapp'

- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',         
          '-t', 
          'gcr.io/$PROJECT_ID/lnldocker-clickapp-$BRANCH_NAME', 
          '.',
        ]
  dir: 'clickapp'

- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',         
          '-t', 
          'gcr.io/$PROJECT_ID/lnldocker-resultapp-$BRANCH_NAME', 
          '.',
        ]
  dir: 'resultapp'
images: 
  - 'gcr.io/$PROJECT_ID/lnldocker-webapp-$BRANCH_NAME'
  - 'gcr.io/$PROJECT_ID/lnldocker-clickapp-$BRANCH_NAME'
  - 'gcr.io/$PROJECT_ID/lnldocker-resultapp-$BRANCH_NAME'