version: '3.3'
services:
    web:
        container_name: lnlwebapp
        build: 
            context: ./webapp
            dockerfile: Dockerfile
        command: nodemon --watch /usr/src/app
        depends_on:
            - nginx
        ports:
          - "3000:8080"
        volumes:
          - type: bind
            source: ./webapp/app/index.js
            target: /usr/src/app/index.js
          - type: bind
            source: ./webapp/app/public
            target: /usr/src/app/public
    click:
        container_name: lnlclickapp
        build: 
            context: ./clickapp
            dockerfile: Dockerfile        
        command: nodemon --watch /usr/src/app
        depends_on:
          - nginx
          - redis
        ports:
          - "4000:8081"        
        volumes:
          - type: bind
            source: ./clickapp/app/index.js
            target: /usr/src/app/index.js
    result:
        container_name: lnlresultapp
        build: 
            context: ./resultapp
            dockerfile: Dockerfile        
        command: nodemon --watch /usr/src/app
        depends_on:
            - nginx
            - redis
        ports:
          - "5000:8080"        
        volumes:
          - type: bind
            source: ./resultapp/app/index.js
            target: /usr/src/app/index.js
    nginx:
        container_name: lnlnginx
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports:
          - "80:8080"
    redis:
        container_name: lnlredis
        build: 
            context: ./redis
            dockerfile: Dockerfile